### ISSUE TITLE
Use organizational projects (beta)

### ISSUE THREAD

**Issue by heaths** [heaths/gh-projects#24]
Repository projects (beta) must be referenced by a repo to be visible. Instead, use organizational projects (beta) using the specified repo owner. Will still need the `--repo` switch for `gh projects edit --add-issue --remove-issue`, though.

**Comment by heaths** [comment]
After some prototyping, I remember why I didn't do this originally: top-level queries for `organization` and `user` are separate, though the `projectNext` connection thereunder is the same. Perhaps in addition to `--repo` I could support `--org` and `--user` - perhaps mutually exclusive, where the latter two require only an owner (`login`, technically, but I'll be consistent) but would accept a full repo spec since the default is to get the current repo anyway, from which we get the owner.

**Comment by heaths** [comment]
Talking with @weshaggard, I'll just make sure that whenever you add or remove an issue (or pull request) from a project I make sure it gets referenced by the issue's repo. If you don't - and I tested this out with a new org project (beta) I created - it doesn't show up as a selection for issues in that repo, even though you can add issues from any of the org's projects from the projects (beta) UI.

**Comment by heaths** [comment]
Unfortunately, it seems there's no way currently to link a repo and a projects (beta): https://github.com/github/feedback/discussions/16168

**Comment by heaths** [comment]
Linking a project to a repo is now supported: https://docs.github.com/en/graphql/reference/input-objects#linkprojectv2torepositoryinput

Still need to query an org or user - can we determine up front which it is, or maybe just query both?

**Comment by heaths** [comment]
Fixed by #40

**Comment by spinningarrow** [comment]
Just ran into this (great tool btw!) but I can't seem to be able to use it for org projects. The `view` and `edit` commands at least don't seem to have a syntax for this - or am I missing something?

**Comment by heaths** [comment]
There's no change in syntax. Any projects V2 (does *not* work with V1 projects, which `gh` already supports) under an org or users - whatever the repo is under - are visible. Older versions of this extension required you first associate the project V2 to your repo, but when GitHub added necessary support I now try to associate the project V2 myself in code. Make sure you're using the latest version: `gh ext upgrade heaths/gh-projects`.

Otherwise, please open a new issue with exact repro steps and I can take a look, but I use this across many users and orgs and haven't run into a problem yet.

**Comment by spinningarrow** [comment]
I must be missing something really basic (I did an upgrade just now, but probably it did nothing since I installed this extension an hour ago). Here's some output of some of the commands, happy to open an issue if you'd like:

```
gh projects list --all
Error: failed to run git: fatal: not a git repository (or any of the parent directories): .git
. error: exit status 128
```
(a little surprising since I'm trying to get projects regardless of repo, but anyway)

```
gh projects list --all --repo '<org>/<repo>'

Showing 6 of 6 projects

#8  <project name>       private  about 8 days ago
#7  <project name>  private  about 8 days ago
#6  <project name>                                     private  about 1 month ago
#5  <project name>                         private  about 1 month ago
#3  <project name>                              private  about 4 months ago
#1  <project name>                        private  about 11 months ago
```

```
gh projects edit 6 --add-issue 203 --repo '<org>/<repo>'
Error: GraphQL: Could not resolve to a ProjectV2 with the number 6. (repository.projectV2)
```

```
gh projects edit '<org>/6' --add-issue 203 --repo '<org>/<repo>'
Error: invalid project number: <org>/6
```
(I use our real org and repo names, just skipped it for privacy)

**Comment by heaths** [comment]
The first command failed because this has to be run in a repo to automatically get org or user information. Same with most `gh` commands, since this just uses the same common library they do / provide.

A repo and project can only belong to one org or user and every repo is under a single org or a single user, so it's just `6` and not anything like `<org>/6`. As to why it's not finding it when you run `edit` you'll need to set `GH_DEBUG="api"` and open a _new_ issue with details. If it's a public repo, not sure why it matters you don't list it; otherwise, you're going to have to mask a lot of text in the debug output I'd need to see to figure out why it's not working for you.

**Comment by spinningarrow** [comment]
Found the reason! The project was not "linked" to the repo; the commands worked after I linked it in the GH web interface. I'm not sure what that changes behind the scenes, since in the web interface I could still connect issues to the project 🤷 

 (thanks for the `GH_DEBUG="api"` tip!)

**Comment by heaths** [comment]
I was able to repro this. Seems GitHub broke something. I'll open a bug.

**Comment by heaths** [comment]
Opened #43 to track.

**Comment by heaths** [comment]
Automatically linking should be fixed now. Run `gh ext upgrade heaths/gh-projects` to get the fix.
