### ISSUE TITLE
Clone a project

### ISSUE THREAD

**Issue by heaths** [heaths/gh-projects#28]
Clone fields, views, etc.

**Comment by heaths** [comment]
Sorry, @jsquire, but this won't be possible right now. I assumed there were more mutations to, for example, create a `ProjectNext` object, but no - not at this time. There is even a GraphQL mutation to clone a project (classic). I did open https://github.com/github-community/community/discussions/18471 for now.

**Comment by jsquire** [comment]
I suppose some gaps are to be expected, given the beta status.   Thanks for looking into it!
