### ISSUE TITLE
newbie token question

### ISSUE THREAD

**Issue by luebken** [heaths/gh-projects#41]
Possibly a silly newbie token question: 

After I've authenticated with `gh auth login` and the browser and I run `gh projects list` I get the following: 

```
$ gh projects list
Error: GraphQL: Your token has not been granted the required scopes to execute this query. The 'projectsV2' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['gist', 'read:org', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens., Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['gist', 'read:org', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens., Your token has not been granted the required scopes to execute this query. The 'number' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['gist', 'read:org', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens., Your token has not been granted the required scopes to execute this query. The 'title' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['gist', 'read:org', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens., Your token has not been granted the required scopes to execute this query. The 'shortDescription' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['gist', 'read:org', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens., Your token has not been granted the required scopes to execute this query. The 'public' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['gist', 'read:org', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens., Your token has not been granted the required scopes to execute this query. The 'createdAt' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['gist', 'read:org', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
```

Could you briefly describe on how I would need to authenticate?

**Comment by heaths** [comment]
In the error message, it reads,

> Please modify your token's scopes at: https://github.com/settings/tokens.

If you go to <https://github.com/settings/tokens>, do you see a token for GitHub CLI? If so, you can go into it and check the "project" scope (you'll need that to make any modifications):

![image](https://user-images.githubusercontent.com/1532486/205990148-48215b83-e34f-4348-9346-7d0ad6e70025.png)

If you don't see it, whenever any GitHub CLI or extension command gives you an error asking for more scopes, you can pass whatever scope it says to the following command e.g.,

```bash
gh auth refresh -s project
```

Follow the instructions it provides to authenticate with additional scopes.

I do check that the caller is authenticated and if not, tell them the command they should use. I'll keep this bug open to track trying to detect the case where this fails and do the same.

**Comment by luebken** [comment]
That worked thanks a lot!

Unfortunatly I'm running to the next permission problem:

```
$ gh projects edit 11 --add-issue 222
Error: failed to link project #11 to "xxx/yyy": GraphQL: luebken does not have the correct permissions to execute `LinkProjectV2ToRepository` (linkProjectV2ToRepository)
```
A search for linkProjectV2ToRepository didnt really result in anything helpful for me.

**Comment by heaths** [comment]
You can only add issues to a project V2 if it's linked to a repository (in order to resolve issue references, etc.). Prior to my latest version, you had to do so manually. Now I attempt to do so automatically (GitHub added linking support to link a project to a repo), but [their docs](https://docs.github.com/en/graphql/reference/mutations#linkprojectv2torepository) didn't say anything about permissions. If you don't have permissions to alter setting of your project (I'm guessing at permissions since it's not documented), you might have to have a repo admin link the project. It's easy enough to do from the repo's "Projects" tab.

**Comment by heaths** [comment]
Since it would be difficult for me to set up a repro where I don't have permissions to link a project, do you have a Go dev environment installed? I could push a change you could pull and run to see what additional information is prints.
