### ISSUE TITLE
view should be able to list unlinked projects

### ISSUE THREAD

**Issue by heaths** [heaths/gh-projects#49]
All commands should be able to work on linked and unlinked projects. For example, `view` only looks at linked projects but I could provide an `--all` that shows all projects. In this case, it would show all items as well. Or, if all items from all linked repos are shown anyway, maybe the query should use `repositoryOwner`.

See [this comment](https://github.com/heaths/gh-projects/issues/43#issuecomment-1456272294) for contexct.

**Comment by heaths** [comment]
Just checked and even within a repo I see items from other repos, so it's worth considering showing all projects by default. It's a regression in behavior, though, but may be acceptable. Ideally, it'd be great to be able to pass either an org/user or a repo for `--repo` but the cli/go-gh library (or even the cli/cli itself) requires a repo scope for auth tokens. This way, a user could implicitly decide whether they want a command to act at an org/user or repo scope. So maybe my own switch would be good.

If I change the default behavior to show all projects, perhaps a switch to limit the scope to just the repo - for items as well. GitHub's GraphQL queries don't currently support filtering by repo, but I could modify https://github.com/heaths/gh-projects/blob/bf17962703056cef3c645caac7a094dede33989d/internal/cmd/view.go#L80-L88 to filter to a repo then compare to `opts.Limit` until filled or exhausted.

Perhaps a `--scope` switch that defaults to `owner` but accepts `repo`. @samcoe, if you don't mind me asking, has the CLI ever given consideration to scoping commands to either an org/user or repo? Off hand, the only scope I'm finding in the cli/cli repo is about oauth scopes, but if there has been some thought to what scoping commands might look like I'd love to be consistent. Though, I imagine the only features where this is even a problem is with regard to projects (v1 or v2) for which the CLI doesn't have a lot of support for now - none for v2; though, I'd be happy to start incorporating a lot of this extension into the CLI if you feel it's ready, as what happened with labels.

**Comment by samcoe** [comment]
@heaths I don't believe we have ever had that conversation about scoping commands. You are right though that the only product that really fits the category of needing scoping is Projects Classic and Projects V2, everything else has pretty clear ownership.

By the way the GitHub Projects team released their own [extension](https://github.blog/changelog/2023-03-02-github-issues-projects-march-2nd-update/#computer-manage-projects-from-the-command-line) that will likely be making its way into CLI core once the bugs and kinks have been worked out.

**Comment by heaths** [comment]
Would it be singular like all other command groups? I specifically made mine plural for that reason - to avoid a conflict like what happened with `label`.

**Comment by samcoe** [comment]
@heaths I believe so, it will be singular.
